export { default as HomePage } from './Home';
export { default as Marketplace } from './MarketPlace';
export { default as Legal } from './Legal';
export { default as TANDC } from './TANDC';
export { default as FAQ } from './FAQ';
export { default as ServiceAgreement } from './ServiceAgreement';
export { default as PrivacyPolicy } from './PrivacyPolicy';
export { default as PageNotFound } from './PageNotFound';
export { default as APIDetailsPage } from './APIDetailsPage';
